#-------------------------------------------------------------------------------
#
# ESLint Configuration, http://eslint.org/docs/user-guide/configuring.
#
#-------------------------------------------------------------------------------

root: true

extends:
  - "defaults"

parserOptions:
  ecmaVersion: 5

env:
  node: true
  mocha: true

rules:
  quotes:
    - "error"
    - "double"

  strict:
    - "error"
    - "function"
