---
root: true

parser: "@typescript-eslint/parser"

plugins:
    - "unused-imports"

extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/eslint-recommended"
    - "plugin:@typescript-eslint/recommended"
    - "prettier"
    - "plugin:security-node/recommended"
    - "plugin:promise/recommended"
    - "plugin:import/recommended"
    - "plugin:jsx-a11y/recommended"

settings:
    import/resolver:
        typescript: true
        node: true

rules:
    # Consistent import order and spacing of imports.
    "import/order":
        - "error"
        - "newlines-between": "always-and-inside-groups"
    "unused-imports/no-unused-imports": "error"
    "unused-imports/no-unused-vars": "warn"

env:
    browser: true
    node: true
