---
name: "release"

on:
    release:
        types: ["published"]

permissions: "read-all"

jobs:
    release:
        runs-on: "ubuntu-latest"

        permissions:
            contents: "read"
            id-token: "write"

        steps:
            - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
            - uses: "pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320"
              with:
                  version: "latest"
            - uses: "actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
                  registry-url: "https://registry.npmjs.org"
            - run: "make install"
            - run: "make audit_signatures"
            - run: "make build"
            - run: "make lint"
            - run: "make test"
            - run: "npm install -g npm@latest"
            - run: "npm publish --no-git-checks"
