---
name: "release"

on:
    release:
        types: ["published"]

permissions: "read-all"

jobs:
    release:
        runs-on: "ubuntu-latest"

        permissions:
            contents: "read"
            id-token: "write"

        steps:
            - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"
            - uses: "pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271"
              with:
                  version: "latest"
            - uses: "actions/setup-node@820762786026740c76f36085b0efc47a31fe5020"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
                  registry-url: "https://registry.npmjs.org"
            - run: "make install"
            - run: "make audit_signatures"
            - run: "make build"
            - run: "make lint"
            - run: "make test"
            - run: "npm install -g npm@latest"
            - run: "npm publish"
