---
name: "sast"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"
    schedule:
        - cron: "19 19 * * 4"

permissions: "read-all"

jobs:
    ossf:
        runs-on: "ubuntu-latest"
        # ossf scorecard only supported on main branch
        if: github.event_name != 'pull_request'
        permissions:
            security-events: "write"
            id-token: "write"
            contents: "read"
            actions: "read"
        steps:
            - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
              with:
                  persist-credentials: false
            - uses: "ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a"
              with:
                  results_file: "results.sarif"
                  results_format: "sarif"
                  publish_results: true
            - uses: "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"
              with:
                  name: "SARIF file"
                  path: "results.sarif"
                  retention-days: 5
            - uses: "github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13"
              with:
                  sarif_file: "results.sarif"

    codeql:
        runs-on: "ubuntu-latest"

        permissions:
            actions: read
            contents: read
            security-events: write

        steps:
            - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
            - uses: "github/codeql-action/init@c10b8064de6f491fea524254123dbe5e09572f13"
              with:
                  languages: "typescript"
            - uses: "pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb"
              with:
                  version: "latest"
            - uses: "actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - run: "make install"
            - uses: "github/codeql-action/analyze@c10b8064de6f491fea524254123dbe5e09572f13"
