---
name: "sast"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"
    schedule:
        - cron: "19 19 * * 4"

permissions: "read-all"

jobs:
    ossf:
        runs-on: "ubuntu-latest"
        # ossf scorecard only supported on main branch
        if: github.event_name != 'pull_request'
        permissions:
            security-events: "write"
            id-token: "write"
            contents: "read"
            actions: "read"
        steps:
            - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
              with:
                  persist-credentials: false
            - uses: "ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a"
              with:
                  results_file: "results.sarif"
                  results_format: "sarif"
                  publish_results: true
            - uses: "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"
              with:
                  name: "SARIF file"
                  path: "results.sarif"
                  retention-days: 5
            - uses: "github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225"
              with:
                  sarif_file: "results.sarif"

    codeql:
        runs-on: "ubuntu-latest"

        permissions:
            actions: read
            contents: read
            security-events: write

        steps:
            - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
            - uses: "github/codeql-action/init@95e58e9a2cdfd71adc6e0353d5c52f41a045d225"
              with:
                  languages: "typescript"
            - uses: "pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53"
              with:
                  version: "latest"
            - uses: "actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - run: "make install"
            - uses: "github/codeql-action/analyze@95e58e9a2cdfd71adc6e0353d5c52f41a045d225"
